default: &default
  adapter: sqlite3
  encoding: unicode

development:
  <<: *default
  database: alarmx_development

test:
  <<: *default
  database: alarmx_test

production:
  <<: *default
  database: alarmx_production

